model:
  height: 50
  width: 50
  class: "BasicModel"
view:
  height: 500
  width: 500
  classes:
  - "SquarePixelsWithBorder"
controller:
  classes:
  - class: SimpleTestGame
    start: .1
    speed: 1000
  - class: ClickController
