model:
  height: 100
  width: 100
  class: "BasicModel"
view:
  height: 800
  width: 800
  classes:
  - "SquarePixelsWithBorder"
controller:
  classes:
  - class: "GameOfLife3"
    speed: 30
    alive:
      r: 0
      g: 0
      b: 0
    dead:
      r: 255
      g: 255
      b: 255
    initialAliveProbability: 0
  - class: "ClickController"
